version: 2
updates:
  # GitHub Actions Updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "github-actions"
    auto-merge: true
    versioning-strategy: increase
  
  # Docker Updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "node"
        versions:
          - "22.x"
    labels:
      - "dependencies"
      - "docker"
    auto-merge: true
    versioning-strategy: increase
  
  # npm Updates
  - package-ecosystem: "npm"
    directory: "/"  # Location of your package.json
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    labels:
      - "dependencies"
      - "npm"
    # Only auto-merge minor and patch updates
    auto-merge: true
    versioning-strategy: increase
    ignore:
      - dependency-name: "express"
        versions:
          - "4.17.1"
      - dependency-type: "development"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore"
      include: "scope"
