version: 2
updates:
  # GitHub Actions Updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "github-actions"
  
  # Docker Updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "node"
        versions:
          - "20.x"
    labels:
      - "dependencies"
      - "docker"
  
  # npm Updates
  - package-ecosystem: "npm"
    directory: "/"  # Location of your package.json
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    ignore:
      - dependency-name: "express"
        versions:
          - ">=5.0.0"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore"
      include: "scope"
