name: 'Pull Request Labeler'
on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Debug PR Info
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          FILES_CHANGED: ${{ toJSON(github.event.pull_request.changed_files) }}
        run: |
          echo "PR Title: $PR_TITLE"
          echo "Files Changed: $FILES_CHANGED"

      - name: Label PR
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
          configuration-path: .github/labeler.yml
          dot: true
