name: Yml Lint

on:
  pull_request:
    paths:
      - '**.yml'

jobs:
  yml-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # not only lints all the yml,
      # but can also detect and prevent injection vulnerabilities in workflows
      - uses: devops-actions/actionlint@v0.1.3
