name: PR Checks
on: [pull_request]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use our composite action for TypeScript setup and checks
      - name: Setup and Test TypeScript
        id: setup
        uses: ./actions/setup-ts-project
        with:
          node-version-file: '.nvmrc'
          install-command: 'npm ci'
          build-command: 'npm run build'
          skip-tests: 'false'

      # Test our actions
      - name: Test Hello World Action
        id: hello
        uses: ./actions/hello-world
        with:
          who-to-greet: 'TypeScript Action Tester'

      - name: Test Goodbye World Action
        id: goodbye
        uses: ./actions/goodbye-world
        with:
          who-to-farewell: ${{ steps.hello.outputs.time }}

      - name: Test Answer Action
        id: answer
        uses: ./actions/answer-action
        with:
          who-to-greet: 'Docker Action Tester'

      - name: Verify Answer
        if: ${{ steps.answer.outputs.answer != '42' }}
        run: |
          echo "::error file=actions/answer-action/entrypoint.sh,line=4,title=Error in container::The answer was not 42"
          exit 1

      - name: Show All Action Outputs
        run: |
          echo "Node.js Version: ${{ steps.setup.outputs.node-version }}"
          echo "Hello World Time: ${{ steps.hello.outputs.time }}"
          echo "Goodbye World Message: ${{ steps.goodbye.outputs.message }}"
          echo "Answer Action Result: ${{ steps.answer.outputs.answer }}"
