name: 'Test Actions'
on: [pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> "$GITHUB_ENV"

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run typecheck
        run: npm run typecheck

      - name: Run lint
        run: npm run lint

      - name: Run Test
        run: npm test

      - name: Run Build
        run: npm run build

      - name: Test Hello World Action
        id: hello
        uses: ./actions/hello-world
        with:
          who-to-greet: 'TypeScript Action Tester'

      - name: Test Goodbye World Action
        id: goodbye
        uses: ./actions/goodbye-world
        with:
          who-to-farewell: ${{ steps.hello.outputs.time }}
